=== vanchann/library_application/storage/game/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="title" type="xs:string">
    <xs:unique name="uniqueTitle">
        <xs:selector xpath="title"/>
        <xs:field xpath="."/>
    </xs:unique>
</xs:element>
<xs:element name="shop" type="xs:string"/>
<xs:element name="finished" type="xs:boolean" default="false"/>
<xs:element name="lastupdated" type="xs:date"/>
<xs:element name="filename" type="xs:string"/>

<!-- definition of simple types -->
<xs:element name="system">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Linux"/>
            <xs:enumeration value="Mac"/>
            <xs:enumeration value="Windows"/>
            <xs:enumeration value="Other"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<!-- definition of complex types -->
<xs:element name="installer">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="system"/>
            <xs:element ref="lastupdated" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="filename" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="game">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="title"/>
            <xs:element ref="shop"/>
            <xs:element ref="finished"/>
            <xs:element ref="installer" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="library">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="game" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== vanchann/library_application/storage/game/library.xml
<?xml version="1.0" encoding="UTF-8"?>

<library
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="library.xsd">
    <game>
        <title>Test</title>
        <shop>DRM-free</shop>
        <finished>Yes</finished>
        <installer>
            <system>Windows</system>
            <lastupdated>2017-07-14</lastupdated>
            <filename>win_file_1</filename>
            <filename>win_file_2</filename>
            <filename>win_file_3</filename>
        </installer>
        <installer>
            <system>Linux</system>
            <filename>lin_file_1</filename>
            <filename>lin_file_2</filename>
        </installer>
    </game>
    <game>
        <title>Test1</title>
        <shop>DRM-free</shop>
        <finished>No</finished>
    </game>
    <game>
        <title>a</title>
        <shop>DRM-free</shop>
        <finished>Yes</finished>
    </game>
    <game>
        <title>A</title>
        <shop>DRM-free</shop>
        <finished>No</finished>
    </game>
</library>
