=== vanchann/library_application/storage/music/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="title">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="artist">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="genre">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="format">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="CD"/>
            <xs:enumeration value="MP3"/>
            <xs:enumeration value="FLAC"/>
            <xs:enumeration value="OGG"/>
            <xs:enumeration value="Other"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="releasedate" type="xs:date"/>

<xs:element name="label">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="track">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="shop">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>


<!-- definition of complex types -->
<xs:element name="genres">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="genre" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="formats">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="format" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="tracks">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="track" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="music">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="title"/>
            <xs:element ref="artist"/>
            <xs:element ref="formats"/>
            <xs:element ref="genres" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="tracks" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="releasedate" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="label" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="shop" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueTrack">
        <xs:selector xpath="tracks/track"/>
        <xs:field xpath="."/>
    </xs:unique>
</xs:element>

<xs:element name="library">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="music" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueTitle">
        <xs:selector xpath="music/title"/>
        <xs:field xpath="."/>
    </xs:unique>
</xs:element>

</xs:schema>

=== vanchann/library_application/testing/library/test_music_library.xml
<?xml version='1.0' encoding='UTF-8'?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
    <music>
        <title>Test</title>
        <artist>Art</artist>
        <formats>
            <format>MP3</format>
            <format>Other</format>
        </formats>
        <genres>
            <genre>Gothic</genre>
            <genre>Rock</genre>
        </genres>
        <tracks>
            <track>One</track>
            <track>Two</track>
        </tracks>
        <releasedate>2007-02-01</releasedate>
        <label>World</label>
        <shop>Shop</shop>
    </music>
    <music>
        <title>Another</title>
        <artist>Art</artist>
        <formats>
            <format>FLAC</format>
        </formats>
        <label>World</label>
        <shop>Shop</shop>
    </music>
</library>

=== vanchann/library_application/testing/library/test_video_library.xml
<?xml version='1.0' encoding='UTF-8'?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
    <video>
        <title>Test</title>
        <formats>
            <format>DVD</format>
            <format>Other</format>
        </formats>
        <genres>
            <genre>Action</genre>
            <genre>Movie</genre>
        </genres>
        <releasedate>2007-06-24</releasedate>
        <label>World</label>
        <shop>Shop</shop>
    </video>
    <video>
        <title>Another</title>
        <formats>
            <format>MP4</format>
        </formats>
        <label>World</label>
        <shop>Shop</shop>
    </video>
</library>
