=== vanchann/library_application/storage/book/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="title">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="author">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="category">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="format">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hardback"/>
            <xs:enumeration value="Paperback"/>
            <xs:enumeration value="eBook"/>
            <xs:enumeration value="Other"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="isbn">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="13"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="publicationdate" type="xs:date"/>

<xs:element name="pagenumber">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="lastpageread">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="publisher">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="edition">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="shop">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="finished">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Yes"/>
            <xs:enumeration value="No"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<!-- definition of complex types -->
<xs:element name="authors">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="author" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="formats">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="format" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="book">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="title"/>
            <xs:element ref="authors"/>
            <xs:element ref="category"/>
            <xs:element ref="formats"/>
            <xs:element ref="isbn"/>
            <xs:element ref="publicationdate" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="publisher" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="edition" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="pagenumber" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="lastpageread" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="shop" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="finished"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="library">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="book" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueIsbn">
        <xs:selector xpath="book/isbn"/>
        <xs:field xpath="."/>
    </xs:unique>
</xs:element>

</xs:schema>

=== vanchann/library_application/testing/library/test_book_library.xml
<?xml version='1.0' encoding='UTF-8'?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd"><book>
        <title>Test</title>
        <authors>
            <author>Someone</author>
            <author>Elseone</author>
        </authors>
        <category>Programming</category>
        <formats>
            <format>Hardback</format>
            <format>eBook</format>
        </formats>
        <isbn>1234567890123</isbn>
        <pagenumber>100</pagenumber>
        <lastpageread>10</lastpageread>
        <shop>Shop</shop>
        <finished>Yes</finished>
    </book>
    <book>
        <title>Test</title>
        <authors>
            <author>Other</author>
        </authors>
        <category>Programming</category>
        <formats>
            <format>Hardback</format>
            <format>eBook</format>
        </formats>
        <isbn>1234567890124</isbn>
        <finished>Yes</finished>
    </book>
</library>
